proj_name: test-18Sv4
raw_data: /vortexfs1/omics/huber/shu/tagseq-qiime2-snakemake/raw_dir
scratch:  /vortexfs1/scratch/sarahhu/tagseq-18S-test
outputDIR: /vortexfs1/omics/huber/shu/tagseq-qiime2-snakemake
manifest: /vortexfs1/omics/huber/shu/tagseq-qiime2-snakemake/raw_dir/manifest-orig.txt
manifest-trimmed: manifest-trimmed.txt

# Fastq file suffix, following the read pair designation
suffix: .fastq.gz
#suffix: _001.fastq.gz

# Read pair designations
r1_suf: 1
r2_suf: 2
#r1_suf: R1
#r2_suf: R2

# QIIME2-specific flags
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.

## 18S default (Stoeck et al. 2010 V4 primers)
primerF: CCAGCASCYGCGGTAATTCC
primerR: ACTTTCGTTCTTGATYRA
primer_err: 0.4
primer_overlap: 3
# Merging reads for 18S:
minoverlap: 10
maxdiff: 4
minlength: 270

## 16S default (Parada et al. modified EMP primers)
#primerF: GTGYCAGCMGCCGCGGTAA
#primerR: GGACTACNVGGGTWTCTAAT
# Parada et al. 2016 MEP primers for 16S
#primer_err: 0.1
#primer_overlap: 3 
# Merging reads for 16S
#minoverlap: 20
#maxdiff: 4
#minlength: 200

## Database
database: /vortexfs1/omics/huber/shu/db/pr2-db/V4-pr2_4.12.0.qza
database_classified: /vortexfs1/omics/huber/shu/db/pr2-db/V4-pr2_4.12.0-classifier.qza
database_tax: /vortexfs1/omics/huber/shu/db/pr2-db/pr2_4.12.0_tax.qza

## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 200
truncation_len-r: 200
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled

## OTU clustering

# Quality filtering of merged reads
minphred: 4
qualwindow: 3 

# De novo OTU clustering
denovo_perc_id: 0.97
denovo_otu-thread: 1

# Chimera checking
chimera-thread: 1
